import type { Metadata } from 'next'
import { Inter as FontSans } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import { SessionWrapper } from '@/contexts/sessionWrapper'
import { Locale } from '@/data/locales'
import { I18nProviderClient } from '@/locales/client'
import { Header } from '@/layout/header/'
import { ThemeWrapper } from '@/contexts/themeWrapper'

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans'
})

export const metadata: Metadata = {
  // TODO generate metada by language
  title: 'Create Next App',
  description: 'Generated by create next app'
}

type Props = {
  children: React.ReactNode
  params: {
    locale: Locale
  }
}

export default function RootLayout({ children, params }: Props) {
  return (
    <SessionWrapper>
      <html lang={params.locale} suppressHydrationWarning>
        <body
          className={cn(
            'flex min-h-screen flex-col bg-background font-sans antialiased',
            fontSans.variable
          )}
        >
          <ThemeWrapper
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            <I18nProviderClient locale={params.locale}>
              <Header />
              <main className="container flex flex-1 flex-col max-sm:px-3">
                {children}
              </main>
            </I18nProviderClient>
          </ThemeWrapper>
        </body>
      </html>
    </SessionWrapper>
  )
}
